#!/bin/sh

SYSLOGD_ARGS=-n
KLOGD_ARGS=-n

printf "Starting logging: "
start-stop-daemon -b -S -q --exec /sbin/syslogd -- $SYSLOGD_ARGS
start-stop-daemon -b -S -q --exec /sbin/klogd -- $KLOGD_ARGS
echo "OK"
